name: AkiraMorita
favicon: null
layout_spectrum: 0.2895076412241906
typography_spectrum: 0.1636722597759217
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.745375560130924
  lightness: 0.03318098862655461
  saturation: 0.37088794028386474
  rhythmicContrast: 0.10181351564824581
purpose: []
